version: "3.8"

services:
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    working_dir: /app
    command: npm run dev

  backend:  # <- yaha galti thi, ab thik hai
    build: ./backend
    volumes:
      - ./backend:/app
      - backend_node_modules:/app/node_modules
    working_dir: /app
    ports:
      - "5000:5000"
    command: npm run dev
    env_file:
      - ./backend/.env

volumes:
  backend_node_modules:
  frontend_node_modules:
